const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#08101e',
  },
  loadingShell: {
    flex: 1,
    backgroundColor: '#08101e',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingTitle: {
    color: '#eef4ff',
    fontSize: 28,
    fontWeight: '800',
  },
  loadingText: {
    color: '#94a6c8',
    marginTop: 12,
    fontSize: 15,
  },
  scrollContent: {
    paddingTop: Platform.OS === 'android' ? 36 : 12,
    paddingBottom: 40,
    paddingHorizontal: 16,
  },
  hero: {
    backgroundColor: '#0f1930',
    borderRadius: 28,
    overflow: 'hidden',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#233456',
  },
  heroImage: {
    width: '100%',
    height: 260,
  },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    padding: 18,
    justifyContent: 'space-between',
    backgroundColor: 'rgba(8,16,30,0.34)',
  },
  brand: {
    color: '#9bb3ff',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#f3f7ff',
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '900',
    marginTop: 10,
    maxWidth: '92%',
  },
  heroSubtitle: {
    color: '#d1dcf5',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    maxWidth: '95%',
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  metricCard: {
    flex: 1,
    backgroundColor: 'rgba(8, 17, 35, 0.74)',
    borderWidth: 1,
    borderColor: 'rgba(143, 171, 255, 0.2)',
    borderRadius: 18,
    padding: 12,
  },
  metricTitle: {
    color: '#8ea5ca',
    fontSize: 12,
    fontWeight: '700',
  },
  metricValue: {
    color: '#f2f6ff',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 6,
  },
  metricNote: {
    color: '#8ea5ca',
    fontSize: 12,
    marginTop: 6,
  },
  statRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  statPill: {
    flex: 1,
    backgroundColor: 'rgba(7, 15, 31, 0.78)',
    borderColor: '#22304a',
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  statPillAccent: {
    borderColor: '#506cff',
    backgroundColor: 'rgba(80, 108, 255, 0.18)',
  },
  statLabel: {
    color: '#94a6c8',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  statValue: {
    color: '#edf4ff',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 6,
  },
  tabRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  tabButton: {
    width: '31%',
    minWidth: 104,
    backgroundColor: '#111b30',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#22304a',
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignItems: 'center',
    gap: 8,
  },
  tabButtonActive: {
    borderColor: '#506cff',
    backgroundColor: '#172646',
  },
  tabText: {
    color: '#a4b7d6',
    fontWeight: '700',
    fontSize: 12,
  },
  tabTextActive: {
    color: '#f1f5ff',
  },
  tabIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
  },
  actionCard: {
    backgroundColor: '#101a31',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#22334f',
    marginBottom: 20,
    overflow: 'hidden',
  },
  actionImage: {
    width: '100%',
    height: 170,
  },
  actionContent: {
    padding: 16,
    gap: 8,
  },
  actionEyebrow: {
    color: '#92a6ce',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  actionTitle: {
    color: '#f3f7ff',
    fontSize: 22,
    fontWeight: '900',
  },
  actionSubtitle: {
    color: '#b8c6de',
    fontSize: 14,
    lineHeight: 20,
  },
  actionProgressShell: {
    height: 14,
    backgroundColor: '#0a1122',
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 4,
    borderWidth: 1,
    borderColor: '#253552',
  },
  actionProgressFill: {
    height: '100%',
    backgroundColor: '#5f7bff',
    borderRadius: 999,
  },
  actionMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 4,
  },
  actionMetaText: {
    color: '#9bb0d7',
    fontSize: 12,
  },
  sectionHeader: {
    marginBottom: 10,
    marginTop: 4,
  },
  sectionTitle: {
    color: '#eef4ff',
    fontSize: 20,
    fontWeight: '800',
  },
  sectionSubtitle: {
    color: '#8fa4cb',
    fontSize: 13,
    marginTop: 4,
  },
  card: {
    backgroundColor: '#0f1930',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#213250',
    padding: 14,
    marginBottom: 12,
  },
  cardTitle: {
    color: '#f3f7ff',
    fontSize: 17,
    fontWeight: '800',
  },
  cardText: {
    color: '#a9bbda',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  cardStrong: {
    color: '#f7fbff',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 8,
  },
  missionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  badge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#31486c',
    backgroundColor: '#091120',
  },
  badgeText: {
    color: '#dce7ff',
    fontSize: 12,
    fontWeight: '800',
  },
  button: {
    backgroundColor: '#5e7aff',
    borderRadius: 16,
    paddingVertical: 11,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    flex: 1,
  },
  buttonSubtle: {
    backgroundColor: '#121f39',
    borderColor: '#32496e',
    borderWidth: 1,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  buttonPressed: {
    transform: [{ scale: 0.985 }],
  },
  buttonText: {
    color: '#f7fbff',
    fontWeight: '800',
    fontSize: 13,
  },
  buttonTextSubtle: {
    color: '#dce7ff',
  },
  rowSpace: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 8,
  },
  gridCard: {
    width: '48%',
    backgroundColor: '#0f1930',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#213250',
    padding: 14,
    marginBottom: 2,
  },
  logCard: {
    backgroundColor: '#0c162a',
    borderWidth: 1,
    borderColor: '#213250',
    borderRadius: 18,
    padding: 12,
    marginBottom: 8,
  },
  logPositive: {
    borderColor: '#1e7d57',
    backgroundColor: '#0f221a',
  },
  logWarning: {
    borderColor: '#8b5e1c',
    backgroundColor: '#251c0f',
  },
  logAccent: {
    borderColor: '#4d62ff',
    backgroundColor: '#101a31',
  },
  logText: {
    color: '#eaf1ff',
    fontSize: 13,
    lineHeight: 18,
  },
  mediaRow: {
    flexDirection: 'row',
    gap: 12,
  },
  cardImage: {
    width: 110,
    height: 110,
    borderRadius: 18,
  },
  marketImage: {
    width: 84,
    height: 84,
    borderRadius: 18,
  },
  mediaContent: {
    flex: 1,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  chip: {
    color: '#d4e0fb',
    backgroundColor: '#0a1222',
    borderWidth: 1,
    borderColor: '#2a3d60',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 11,
    overflow: 'hidden',
  },
  chipPositive: {
    borderColor: '#1e8e61',
    color: '#a7ffd4',
  },
  chipNegative: {
    borderColor: '#9c4759',
    color: '#ffd1db',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  chartRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
    height: 58,
    marginTop: 8,
  },
  chartBarWrap: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  chartBar: {
    borderRadius: 4,
  },
  chartBarPositive: {
    backgroundColor: '#63e3a6',
  },
  chartBarNegative: {
    backgroundColor: '#ff8aa3',
  },
  profileStatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 12,
  },
});

export default App;
